package:
  name: q2-demux
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  build:
  - python {{ python }}
  - nodejs
  - setuptools
  - versioningit
  host:
  - python {{ python }}
  - pip
  - setuptools
  - versioningit
  - wheel
  run:
  - python {{ python }}
  - pandas {{ pandas }}
  - numpy {{ numpy }}
  - scikit-bio {{ scikit_bio }}
  - seaborn {{ seaborn }}
  - pyyaml
  - psutil
  - ipywidgets
  - qiime2 >={{ qiime2 }}
  - q2templates >={{ q2templates }}
  - q2-types >={{ q2_types }}
test:
  requires:
  - qiime2 >={{ qiime2 }}
  - q2templates >={{ q2templates }}
  - q2-types >={{ q2_types }}
  - pytest
  imports:
  - q2_demux
  - qiime2.plugins.demux
  commands:
  - py.test --pyargs q2_demux
about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
