{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-demux
  version: {{ version }}

source:
  path: ../..
build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
    - nodejs

  run:
    - python {{ python }}
    - pandas
    - numpy
    - scikit-bio
    - seaborn >=0.8.1
    - pyyaml
    - psutil
    # `ipywidgets` included to avoid ShimWarning from
    # `seaborn` imports:
    #  https://github.com/mwaskom/seaborn/issues/874
    - ipywidgets
    - qiime2 {{ qiime2 }}
    - q2templates {{ q2templates }}
    - q2-types {{ q2_types }}

test:
  requires:
    - pytest

  imports:
    - q2_demux
    - qiime2.plugins.demux

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
